# Generated by Django 5.0.6 on 2024-06-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("number", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
