# Generated by Django 5.0.6 on 2024-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("url2", models.URLField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("number", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
