# Generated by Django 5.0.6 on 2024-06-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="url2",
            field=models.URLField(blank=True, null=True),
        ),
    ]
