# Generated by Django 5.0.6 on 2024-06-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
