# Generated by Django 5.0.6 on 2024-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_song_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="number",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
