# Generated by Django 5.0.6 on 2024-10-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_alter_song_number_alter_song_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="number",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
